# Generated by Django 5.1.13 on 2025-10-06 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_datoscliente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelos.biblioteca'),
        ),
    ]
